constitution:
  - changed-files:
      - any-glob-to-any-file: '*'
      - any-glob-to-any-file: buildSrc/**

resume:
  - changed-files:
      - any-glob-to-any-file: résumé/**

site:
  - changed-files:
      - any-glob-to-any-file: site/**

demo:
  - changed-files:
      - any-glob-to-any-file:
          - journal/**
          - tracks/**
          - .saga-notes/.rdd13r-notes/**

meta:
  - changed-files:
    - any-glob-to-any-file: .github/**
    - any-glob-to-any-file: releases/**
    - any-glob-to-any-file: gradle.properties
