---
engines:
  eslint-8:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  prettier:
    enabled: true
  bandit:
    enabled: true
  semgrep:
    enabled: true
  detekt:
    enabled: true
  pmd-7:
    enabled: true

exclude_paths:
  - .github/
  - .idea/
  - .run/
  - .saga-notes/
  - build/
  - dist/
  - vendor/
  - node_modules/
  - out/
  - .local/
  - résumé/
  - "**/*.min.js"
  - "**/tests/**"

languages:
  python:
    extensions:
      - ".py"
  css:
    enabled: false
  java:
    enabled: false
  scala:
    enabled: false
  go:
    enabled: false
  ruby:
    enabled: false

commit:
  enabled: true
