source 'https://rubygems.org'

gem 'logger'
gem 'csv'
gem 'ostruct'
gem 'base64'
gem 'bigdecimal'

gem 'jekyll', '~> 4.4.1'
gem 'jekyll-remote-theme', '~> 0.4.3'

group :jekyll_plugins do
  gem 'jekyll-archives'
  gem 'jekyll-paginate-v2'
  gem 'jekyll-include-cache'
  gem 'jekyll-asciidoc'
  gem 'jekyll-data'
  gem 'jekyll-feed'
  gem 'jekyll-gist'
  gem 'jekyll-sitemap'
  gem 'jekyll-algolia'
end
