name: Release Notes Commit
description: "Commit release notes file changes expected in /releases/vX.X.X.md"
author: "VK (rdd13r)"
branding:
  icon: "upload"
  color: "green"

inputs:
  version:
    description: "Release version"
    required: true
  message:
    description: "Commit message"
    required: true
outputs:
  pushed:
    description: "Whether the release notes file was committed and pushed"
    value: ${{ steps.update.outputs.pushed }}

runs:
  using: "composite"

  steps:

    - name: Configure Git Identity
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        echo "::notice title=Setting Up Git::$(git --version)"

    - name: Commit Release Notes
      id: update
      shell: bash
      run: |
        VERSION="${{ inputs.version }}"
        MESSAGE="${{ inputs.message }}"
        RELEASE_FILE="releases/v${VERSION}.md"
        
        if [[ -f "$RELEASE_FILE" ]]; then
        
          echo "::notice title=Committing Release File::$RELEASE_FILE: $MESSAGE"
          git add "$RELEASE_FILE"
          git commit -m "$MESSAGE"
          BRANCH="${GITHUB_HEAD_REF:-$(git rev-parse --abbrev-ref HEAD)}"
          if output=$(git push origin "HEAD:$BRANCH" --porcelain); then
            echo "::notice title=Pushed Release File::Pushed footer to $Branch,see $output"
            echo "pushed=true" >> $GITHUB_OUTPUT
          else
            echo "::error title=Git Push Failed::Push to HEAD:$BRANCH failed. Investigate detached HEAD!"
            echo "pushed=false" >> $GITHUB_OUTPUT
          fi
        
        else
          echo "::error title=Release file NOT found::$RELEASE_FILE"
        fi
