name: Detect Runner Type"
description: "Outputs whether we're running on self-hosted infra or a hosted GitHub runner"
author: "VK (rdd13r)"
branding:
  icon: "server"
  color: "red"

outputs:
  is-self-hosted:
    description: "true if running on a self-hosted runner"
    value: ${{ steps.detect.outputs.self }}

runs:
  using: "composite"
  steps:
    - id: detect
      shell: zsh -l {0}
      run: |
        echo "Runner labels: $RUNNER_LABELS"
        if [[ "$RUNNER_LABELS" == *"self-hosted"* ]]; then
          echo "::notice title=✅ Self-hosted runner::Running on self-hosted dedicated infrastructure."
          echo "is-self-hosted=true" >> $GITHUB_OUTPUT
        else
          echo "::notice title=🌀 Hosted runner::Running on GitHub-hosted collective farm infrastructure."
          echo "is-self-hosted=false" >> $GITHUB_OUTPUT
        fi
