---
categories: [adventures]
tags: [Discord]
excerpt: >
  Torvalds style rant -- Most aggressive startups leverage LLMs against laggards first...
classes: wide
comments: true
---
= Dev Millionaires: "Laggards are a renewable resource"?!
rdd13r

 On a hacker community Discord:
 A brutal riff and a dispatch.

> Captured rant Torvalds style.

The craze continues as OpenAI CEO, Sam Altman, met with the USA Congress to promote his industry through mass hysteria
-- calling to regulate AI immediately.
Or what?!
Well, he doesn't know... _**Save this article** - because I will tell you how this will go_, and you can come back here in a decade or so and admire how I steered you right.

Regulating AI is an idea as impotent as regulating firearms.
Because it is wrong in the abstract, so it can never possibly be right in any concrete.
We should instead be regulating human behavior in all cases.
The root cause of the problem is the Social Contract failure - it always has been.
Unless, of course, guns kill all by themselves like the AI will (actually, it already has, but we'll get more on that later).
Our brilliant approach to regulating 'Guns' led to extremely lucrative arms industry development.
And our brilliant approach to the regulation of nuclear power, nuclear, as in the most necessary milestone in the current phase of humanity's evolution, which in hind site became obvious even a nincompoop, led to record economic stagnation.
So, by all means, let's apply the same wisdom and reasoning (or the lack there of) again to the next most powerful development in civilization, shell we!?
And we will!
But what should _you_, a reasonable individual do?

I'd already written about the Hacker Craze of the 90s here, and this new development with the AI is just the continuation of the same public mass-manipulation.
The evolution of AI and the software in general cannot be stopped or managed by regulation, at most, slowed down by a tiny margin at a staggering cost to the wetware of government attempting to do so.
What we can, and should do by regulation, is influence how people use technology and use natural evolution in general.
If that statement made little sense to you, then there's little reason for you to keep reading my rant here because what follows will make even less sense to you - this topic is not for you, friend.

However, if you are still reading, then there's a point for us to contemplate together.
Social contract has only ever worked in one way: real individual consequences applied to the effects that one causes, not to intentions, not to causes, only the effects.
This is sound in the abstract and thus is effective in regulating herd behavior wherever applied correctly.
I can elaborate indefinitely, but it's the conclusion that's important: government up to and including the point of its conceptual then complete and utter failure, will not be able to manage innovation and evolution as it hasn't been able to do so thus far.

Apparently, 2023 has uncloaked a new breed of millionaire developers!
'Bit-North (BN)', formally named so on its Tor home, also known as the North click, North-East, or Northern, has shattered its "Rich hacker, poor hacker" stereotype.
Wrapping up on May 13th in Québec, this clique-drawn motley of coding enthusiasts.
It is steered this year by a University of Waterloo upstart.
It has become an epicenter for idea exchange and a launchpad for teams targeting the upcoming Hack-a-tron Season 4 and beyond.
Alas, enjoying my new baby duties, I'll sit this one out.

BN, with roots deep in the MIT hacker culture of the 50s, bloomed in the early 90s.
Enduring cycles of growth and decline, akin to its American peers, this community received a lifeline when hacker Paul Jarvis penned, "Company of One: Why Staying Small Is the Next Big Thing for Business."
This ignited a BN revival, drawing over 500 Discord participants and 200 in-person attendees in 2023, forming a global network of like-minded groups fostering disruptive software for years.

The true allure of this community lies in the late 90s-introduced member surveys - no other clicks we know polls its members.
Despite the strict anti-commercialization manifesto held by its three dozen cliques, BN has thrived, presumably due to its core principles.
However, the capitalist pulse of economic and technological advancement throbs within, as many one or two-person companies prosper, prompting, albeit optional, 'money on tech' disclosure.
This year, within a few months, the community pocketed over $10M in contracts, astonishingly from the most conservative industries.
Insurance, banking, and healthcare emerged as top clients, with over 30% of participants cashing in on emerging ML trends, often ignored by these traditional sectors.
_Nothing sold here is an asset!
And Nothing took more than a couple dev-months to build._

In a remarkable and unexpected twist, the industry's late adopters promptly bought some bespoke AI integration from small hacker groups,
the kind of nimble wins unattainable with their existing 'preferred vendors'!

While on diaper duty, I had a peace of mind to think this through.
If this indeed is true, then this can only be a temporary fluke!

But what's important -- *_never fail to seas the moment!_*
We can learn something from these hustlers.
And I should probably share the scuttlebutt.

== ToDo: Research & Analysis

- 🚨 The Regulatory Fiasco
- ⚔️ The Real Root Problem
- 💰 Bit-North Gets Rich
- 🧪 This Won’t Last
- ✍️ Lessons and Scuttlebutt

'''

_Not published publicly._
