#!/usr/bin/env zsh

# Sync site/.asciidoctorconfig.adoc from site/_config.yml > asciidoctor.attributes.
# Source of truth: _config.yml (what Jekyll reads).
# Target: .asciidoctorconfig.adoc (what the JetBrains AsciiDoc plugin reads).
# Run whenever you add, change, or remove a site-wide AsciiDoc attribute.

INVOKED_PATH=$(pwd)
PROJECT_ROOT=$(git rev-parse --show-toplevel)
CONFIG=$PROJECT_ROOT/site/_config.yml
TARGET=$PROJECT_ROOT/site/.asciidoctorconfig.adoc

printf 'Sync AsciiDoc Attributes:
invocation path : %s
project root    : %s
source          : %s
target          : %s

' $INVOKED_PATH $PROJECT_ROOT $CONFIG $TARGET

[[ -f $CONFIG ]] || { print "Source missing: $CONFIG"; exit 1 }

CONFIG=$CONFIG TARGET=$TARGET ruby -ryaml <<'RUBY'
src = ENV.fetch('CONFIG')
dst = ENV.fetch('TARGET')
cfg = YAML.load_file(src)
attrs = cfg.dig('asciidoctor', 'attributes')

unless attrs.is_a?(Hash)
  warn "Expected asciidoctor.attributes to be a Hash. Got: #{attrs.class}"
  exit 1
end

header = [
  '// IDE mirror of `_config.yml` > `asciidoctor.attributes`.',
  '// Regenerated by src/main/sh/sync-asciidoc-config.sh -- do not edit by hand.',
  '// JetBrains plugin reads this; Jekyll does not.',
  '// Jekyll reads `_config.yml`; the plugin does not.',
  '',
]

lines = attrs.map do |name, value|
  # Strip trailing "@" -- Asciidoctor's soft-override marker, irrelevant to IDE preview.
  v = value.to_s.sub(/@\z/, '')
  ":#{name}: #{v}"
end

File.write(dst, (header + lines).join("\n") + "\n")
puts "Wrote #{attrs.size} attribute(s) to #{dst}"
RUBY

print "\n=== Resulting $TARGET ==="
cat $TARGET
