name: Label Pull Request
run-name: "Labeled Pull Request examining content on ${{ github.actor }} with ${{ github.event_name }}"
#.github/workflows/custom-pr-labels.yml
# https://github.com/actions/labeler

on:
  workflow_dispatch:
  workflow_call:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: riddles-labeling-group
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:

  label-pull-request-iaw-labeling-guidelines:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    name: "Label Pull Request with IAW Labeling Guidelines examining content"

    steps:
      - name: "Label Pull Request pushing labels to GitHub Pull Request"
        uses: actions/labeler@v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
