name: Label Pull Request
run-name: "Labeled Pull Request examining content on ${{ github.actor }} with ${{ github.event_name }}"
#.github/workflows/custom-pr-labels.yml
# https://github.com/actions/labeler

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: riddles-labeling-group
  cancel-in-progress: true

defaults:
  run:
    shell: zsh -l {0}

jobs:

  label-pull-request-iaw-labeling-guidelines:
    timeout-minutes: 2
    runs-on: self-hosted
    name: "Label Pull Request with IAW Labeling Guidelines examining content"

    steps:
      - name: "Label Pull Request pushing labels to GitHub Pull Request"
        uses: actions/labeler@v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
