name: Security Scan by Snyk
run-name: "Executed Security Scan by Snyk on ${{ github.repository }} by ${{ github.actor }} with ${{ github.event_name }} (Attempt ${{ github.run_attempt }})"
#.github/workflows/security-scan-by-snyk.yml
# See der-jynK https://github.com/snyk/actions/tree/master/setup

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  schedule:
    - cron: '23 17 4 * *'

permissions:
  contents: read
  security-events: write

defaults:
  run:
    shell: bash

jobs:

  snyk-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 11

    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0


      - name: Setup Java
        uses: actions/setup-java@v4.7.1
        timeout-minutes: 5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.2
        timeout-minutes: 5
        with:
          gradle-version: 9.0.0


      - name: Run Snyk directly from trunk
        timeout-minutes: 5
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_PROJECT_TOKEN }}
